name: "Pull Request Docs Check"
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - run: ls -al
    - uses: actions/checkout@v3
      with:
        repository: Sungmo-OSS-Project/txt_game_prototype
        path: 'repo'
    - run: ls -al repo
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx_rtd_theme"
        docs-folder: "docs/"
    - run: tree -a
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/
    # # Publish built docs to gh-pages branch.
    # # ===============================
    # - name: Commit documentation changes
    #   run: |
    #     git clone https://github.com/Halozhan/Study-Gtihub-Actions.git --branch gh-pages --single-branch gh-pages
    #     cp -r ../docs/build/html/* gh-pages/
    #     cd gh-pages
    #     touch .nojekyll
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git commit -m "Update documentation" -a || true
    #     # The above command will fail if no changes were present, so we ignore
    #     # that.
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: gh-pages
    #     directory: gh-pages
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # # =============================== write Permissions가 있으면 해결될 것 같은 주석
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/docs'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
    - run: tree -a
